### ISSUE TITLE
Le premier message de chat ne s'affiche pas

### ISSUE THREAD

**Issue by ChavFDG** [ChavFDG/Stolons#17]
Le tout premier message du chat ne s'affiche pas.
C'est très probablement du au fait que n'ayant pas de message on ne peut envoyer l'heure du dernier message pour recevoir les messages suivants. Donc ça merde :)

**Comment by ChavFDG** [comment]
Quand il n'y a aucun message sur le chat, le serveur a des plantages vu qu'on envoie une demande de récupération des derniers messages du chat sur l'heure du dernier message qu'on a mais qu'on en a pas ...

Voilà le log serveur : 

Nov 13 10:15:02 stolons-demo xvfb-run[19159]: info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
Nov 13 10:15:02 stolons-demo xvfb-run[19159]:       Request starting HTTP/1.1 POST http://beta.stolons.org/Chat/GetNewMessages  0
Nov 13 10:15:02 stolons-demo xvfb-run[19159]: info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
Nov 13 10:15:02 stolons-demo xvfb-run[19159]:       Executing action method Stolons.Controllers.ChatController.GetNewMessages (Stolons) with arguments (01/01/0001 00:00:00) - ModelState is Valid
Nov 13 10:15:02 stolons-demo xvfb-run[19159]: info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
Nov 13 10:15:02 stolons-demo xvfb-run[19159]:       Executed action Stolons.Controllers.ChatController.GetNewMessages (Stolons) in 1.7757ms
Nov 13 10:15:02 stolons-demo xvfb-run[19159]: fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[0]
Nov 13 10:15:02 stolons-demo xvfb-run[19159]:       An unhandled exception has occurred: Value cannot be null.
Nov 13 10:15:02 stolons-demo xvfb-run[19159]:       Parameter name: keyValues
Nov 13 10:15:02 stolons-demo xvfb-run[19159]: System.ArgumentNullException: Value cannot be null.
Nov 13 10:15:02 stolons-demo xvfb-run[19159]: Parameter name: keyValues
Nov 13 10:15:02 stolons-demo xvfb-run[19159]:    at Microsoft.EntityFrameworkCore.Internal.EntityFinder`1.FindTracked(Object[] keyValues, IReadOnlyList`1& keyProperties)
Nov 13 10:15:02 stolons-demo xvfb-run[19159]:    at Microsoft.EntityFrameworkCore.Internal.EntityFinder`1.FindAsync(Object[] keyValues, CancellationToken cancellationToken)
Nov 13 10:15:02 stolons-demo xvfb-run[19159]:    at Microsoft.EntityFrameworkCore.DbContext.FindAsync[TEntity](Object[] keyValues, CancellationToken cancellationToken)
Nov 13 10:15:02 stolons-demo xvfb-run[19159]:    at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.FindAsync(Object[] keyValues, CancellationToken cancellationToken)
Nov 13 10:15:02 stolons-demo xvfb-run[19159]:    at Microsoft.AspNetCore.Identity.EntityFrameworkCore.UserStore`9.FindByIdAsync(String userId, CancellationToken cancellationToken)
Nov 13 10:15:02 stolons-demo xvfb-run[19159]:    at Microsoft.AspNetCore.Identity.UserManager`1.FindByIdAsync(String userId)
Nov 13 10:15:02 stolons-demo xvfb-run[19159]:    at Stolons.Controllers.BaseController.GetCurrentAdherentSync() in /srv/stolons/Stolons/Controllers/BaseController.cs:line 87
Nov 13 10:15:02 stolons-demo xvfb-run[19159]:    at Stolons.Controllers.BaseController.GetActiveAdherentStolon() in /srv/stolons/Stolons/Controllers/BaseController.cs:line 105
Nov 13 10:15:02 stolons-demo xvfb-run[19159]:    at Stolons.Controllers.ChatController.GetNewMessages(DateTime date) in /srv/stolons/Stolons/Controllers/ChatController.cs:line 67
Nov 13 10:15:02 stolons-demo xvfb-run[19159]:    at lambda_method(Closure , Object , Object[] )
